import re
import time
import os
import logging
from typing import Dict, List, Tuple
from fastapi import Request, HTTPException, status

logger = logging.getLogger(__name__)

# --- RATE LIMITER CONFIG (In-Memory IP Bucket) ---
# Simple rate limiter: stores timestamps of client requests
_IP_REQUESTS: Dict[str, List[float]] = {}
LIMIT_WINDOW = 60.0  # seconds
LIMIT_MAX_REQUESTS = 60  # per client per window

def check_rate_limit(client_ip: str) -> bool:
    """Checks if a client has exceeded request limits in the sliding window."""
    now = time.time()
    if client_ip not in _IP_REQUESTS:
        _IP_REQUESTS[client_ip] = [now]
        return True

    # Filter out timestamps older than the window
    timestamps = [t for t in _IP_REQUESTS[client_ip] if now - t < LIMIT_WINDOW]
    timestamps.append(now)
    _IP_REQUESTS[client_ip] = timestamps

    return len(timestamps) <= LIMIT_MAX_REQUESTS


# --- SQL INJECTION & SAFETY SANITIZER ---
# Strict regex-based validator for natural language to SQL outputs
SQL_COMMENT_PATTERN = re.compile(r"(--|/\*|\*/|\#)")
UNSAFE_SQL_KEYWORDS = ["DROP", "INSERT", "UPDATE", "DELETE", "CREATE", "ALTER", "GRANT", "REPLACE", "TRUNCATE", "PRAGMA", "ATTACH", "DETACH"]

def is_sql_query_safe(sql: str) -> Tuple[bool, str]:
    """
    Validates a SQL statement generated by LLM for safe execution.
    Returns (is_safe, error_reason).
    """
    cleaned = sql.strip()
    if not cleaned:
        return False, "Empty query"

    cleaned_upper = cleaned.upper()

    # Must start with SELECT
    if not cleaned_upper.startswith("SELECT"):
        return False, "Only SELECT statements are permitted"

    # Must block SQL comments
    if SQL_COMMENT_PATTERN.search(cleaned):
        return False, "Comments (-- or /* */ or #) are not allowed in queries"

    # Must block mutating keywords
    for keyword in UNSAFE_SQL_KEYWORDS:
        # Check word boundaries to avoid false positives (e.g. column named 'created_at')
        if re.search(r"\b" + keyword + r"\b", cleaned_upper):
            return False, f"Unauthorized SQL operation keyword detected: {keyword}"

    return True, "Safe"


# --- PROMPT INJECTION PREVENTION ---
PROMPT_INJECTION_SIGNATURES = [
    r"ignore\s+(all\s+)?previous\s+instructions",
    r"bypass\s+the\s+rules",
    r"system\s+prompt",
    r"you\s+must\s+now\s+play\s+the\s+role",
    r"dan\s+mode",
    r"jailbreak",
    r"ignore\s+above",
    r"forget\s+what\s+i\s+said",
]

def check_prompt_injection(user_message: str) -> bool:
    """
    Checks if a user query matches common prompt injection signatures.
    Returns True if an injection attempt is detected.
    """
    message_lower = user_message.lower()
    for pattern in PROMPT_INJECTION_SIGNATURES:
        if re.search(pattern, message_lower):
            logger.warning(f"SECURITY: Blocked possible prompt injection attempt matching pattern: '{pattern}'")
            return True
    return False


# --- ENVIRONMENT AUDITOR ---
CRITICAL_ENV_VARS = ["SUPABASE_URL", "SUPABASE_SERVICE_KEY", "SECRET_KEY", "GROQ_API_KEY"]

def audit_environment() -> List[str]:
    """Audits local variables and returns warning list of missing variables."""
    missing = []
    for var in CRITICAL_ENV_VARS:
        if not os.getenv(var):
            missing.append(var)
    if missing:
        logger.warning(f"ENV AUDIT: Missing security/API credentials: {', '.join(missing)}")
    else:
        logger.info("ENV AUDIT: All production-critical env variables verified.")
    return missing
